/**
 * This module provides the {@linkcode SourceFile} class, an abstraction over a
 * single source file in a particular project. Its primary purpose is to house
 * the source code of a text-based file that is being linted.
 *
 * ### Source Code Representation
 *
 * The source code is stored internally as a buffer of binary data (raw bytes),
 * which is then decoded into a string using the appropriate text encoding. The
 * public API of the class exposes the source code primarily as a string, for
 * ease of use and manipulation, while also allowing access to the raw buffer
 * for more advanced use cases. This is done to maximize performance during
 * transport and manipulation operations, without sacrificing usability.
 *
 * ### Diagnostics
 *
 * The class also provides a mechanism for storing and managing diagnostic
 * messages that are generated during the linting process. These messages are
 * stored as instances of the {@linkcode Diagnostic} class, which encapsulates
 * information about the location, severity, and message of the diagnostic.
 *
 * #### Snapshotting and "Dirty" State
 *
 * When the linter is run on a source file, any diagnostics that are generated
 * will be stored in the `diagnostics` property of the `SourceFile` instance.
 * The contents of the file at the time of linting are internally snapshotted
 * and associated with the diagnostics, which allows the SourceFile to signal
 * that it has been modified in the meantime, indicating that the diagnostics
 * may no longer be valid.
 *
 * ### Manipulation
 *
 * Instances of the `SourceFile` class also implement several utility methods
 * for manipulating the source code, either as a whole or in parts (e.g., by
 * extracting a range of lines or characters).
 *
 * #### Lint Fixes
 *
 * The class also provides methods for applying fix suggestions to the source
 * code, such as those generated by the {@link Linter} for supported rules.
 *
 * ```ts
 * import { SourceFile } from "jsr:@nick/lint";
 * ```
 *
 * @see {@linkcode LintFix} and {@linkcode LintFixChange} for more info.
 *
 * @module source-file
 */
// import { Position, type PositionLike } from "@nick/fsxx/position";
// import { TextRange } from "@nick/fsxx/text-range";
// import { TextSpan } from "@nick/fsxx/text-span";
import type { PathLike } from "@nick/fsxx/path";
import { SourceFile as SourceFileBase } from "@nick/fsxx/source-file";
import { LintFix } from "./fix.ts";
import type { LintDiagnostic } from "./diagnostic.ts";
import type { Linter } from "./linter.ts";
import { LintRule } from "./rule.ts";
import { Rule, Tag, TagLike } from "./rules.generated.ts";
import type { InputType, MediaType } from "./types.ts";
import type { Config } from "./config.ts";
import { wasm } from "./wasm.ts";

/**
 * Represents a single source file in a project, encapsulating its source code
 * and any diagnostics that have been generated for it.
 */
export class SourceFile extends SourceFileBase {
  #linter: Linter;
  #originalText: string | undefined;
  #diagnostics: LintDiagnostic[] | undefined;
  #fixes: LintFix[] | undefined;
  #rules: LintRule[] | undefined;
  #tags: Tag[] | undefined;
  #mediaType?: MediaType;
  #dirty = false;

  /**
   * Creates a new `SourceFile` instance.
   *
   * @param path The path to the source file.
   * @param source The source code of the file.
   * @param linter The linter instance used for linting the file.
   * @param [mediaType] The media type of the file (optional).
   */
  constructor(
    path: PathLike,
    source: InputType,
    linter: Linter,
    mediaType?: MediaType,
  ) {
    // normalize all inputs into Uint8Array buffers
    if (typeof source !== "string") {
      source = new TextDecoder().decode(source);
    }
    const buf = new TextEncoder().encode(source);
    super(path, buf, "\n");
    this.#linter = linter;
    this.#mediaType = mediaType;
    this.#update_diagnostics();
  }

  #update_diagnostics = (config?: Config) => {
    this.#diagnostics = [
      ...this.linter.lint(this.text, {
        ...config,
        linter: {
          ...config?.linter ?? {},
          specifier: this.path.toString(),
        },
      }),
    ];
    return this;
  };

  #update_fixes = () => {
    this.#fixes = this.diagnostics.reduce(
      (a, d) => a.concat(d.fixes),
      [] as LintFix[],
    );
    return this;
  };

  #update_rules = () => {
    this.#rules = this.diagnostics.reduce(
      (a, d) => a.concat(d.rule),
      [] as LintRule[],
    ).filter((r, i, a) => a.indexOf(r) === i);
    return this;
  };

  #update_tags = () => {
    this.#tags = this.rules
      .flatMap((r) => r.tags)
      .filter((t, i, a) => a.indexOf(t) === i);
    return this;
  }


  #apply_fix = (index: number): this => {
    const text = this.originalText;
    const fix = this.fixes[index];
    if (fix) this.buffer = fix.apply(text);
    this.dirty ||= this.text !== text;
    return this;
  }

  #apply_fixes = (...fixes: LintFix[]): this => {
    if (this.dirty) {
      this.fixes.length = 0;
    } else if (fixes.length) {
      this.#fixes = [...new Set(this.fixes.concat(fixes))];
    }
    const unsorted = this.fixes.splice(0);
    const sorted = wasm.sortFixesOverall(unsorted).map(LintFix.from);
    const text = this.originalText;
    this.buffer = wasm.applyFixes(text, sorted);
    this.dirty ||= this.text !== text;
    return this;
  }

  get originalText(): string {
    return this.#originalText ??= this.outerText;
  }

  /**
   * Gets the media type of the source file.
   */
  get mediaType(): MediaType | undefined {
    return this.#mediaType;
  }

  /**
   * Gets the linter instance used for linting the source file.
   */
  get linter(): Linter {
    return this.#linter;
  }

  /**
   * Gets the list of diagnostics generated for the source file.
   */
  get diagnostics(): readonly LintDiagnostic[] {
    return this.#diagnostics ?? this.#update_diagnostics().#diagnostics!;
  }

  /**
   * Gets the list of lint fixes generated for the source file.
   */
  get fixes(): LintFix[] {
    return this.#fixes ?? this.#update_fixes().#fixes!;
  }

  /**
   * Gets the list of rules applied to the source file.
   */
  get rules(): LintRule[] {
    return this.#rules ?? this.#update_rules().#rules!;
  }

  /**
   * Gets the list of tags associated with the source file.
   */
  get tags(): Tag[] {
    return this.#tags ?? this.#update_tags().#tags!;
  }

  /**
   * Gets the dirty state of the source file.
   */
  get dirty(): boolean {
    return this.#dirty ??= false;
  }

  /**
   * Sets the dirty state of the source file.
   */
  set dirty(value: boolean) {
    this.#dirty = !!value;
  }

  /**
   * Sets the associated {@linkcode Linter} instance for the source file.
   *
   * @param linter The linter instance to set.
   * @return The current instance of the source file, for method chaining.
   */
  setLinter(linter: Linter): this {
    this.#linter = linter;
    return this;
  }

  /**
   * Sets the original text of the source file.
   *
   * @param text The original text to set.
   * @return The current instance of the source file, for method chaining.
   */
  setOriginalText(text: string): this {
    this.#originalText = text;
    return this;
  }

  /**
   * Sets the media type of the source file.
   *
   * @param mediaType The media type to set.
   * @return The current instance of the source file, for method chaining.
   */
  setMediaType(mediaType: MediaType): this {
    this.#mediaType = mediaType;
    return this;
  }

  /**
   * Sets the diagnostics for the source file.
   *
   * @param diagnostics The diagnostics to set.
   * @return The current instance of the source file, for method chaining.
   */
  setDiagnostics(diagnostics: LintDiagnostic[]): this {
    this.#diagnostics = diagnostics;
    return this;
  }

  /**
   * Sets the fixes for the source file.
   *
   * @param fixes The fixes to set.
   * @return The current instance of the source file, for method chaining.
   */
  setFixes(fixes: LintFix[]): this {
    this.#fixes = fixes.map(LintFix.from);
    return this;
  }

  /**
   * Sets the rules for the source file. These will be reflected in the `rules`
   * property of the source file instance, and are intended to correspond with
   * the rules that triggered the diagnostics generated by the linter.
   *
   * @param rules The rules to set.
   * @return The current instance of the source file, for method chaining.
   */
  setRules(rules: (LintRule | Rule)[]): this {
    this.#rules = rules.map(LintRule.from);
    return this;
  }

  /**
   * Sets the tags for the source file. These are passed to the underlying
   * {@linkcode Linter} instance when linting the file, and are used to enable
   * multiple rules at once. The default value is `["recommended"]`.
   *
   * @param tags The tags to set.
   * @return The current instance of the source file, for method chaining.
   */
  setTags(tags: TagLike[]): this {
    this.#tags = tags.map(Tag.from);
    return this;
  }

  addRule(rule: LintRule): this {
    this.rules.push(rule);
    return this;
  }

  addDiagnostic(diagnostic: LintDiagnostic): this {
    this.#diagnostics?.push(diagnostic);
    return this;
  }

  addFix(fix: LintFix): this {
    this.fixes.push(fix);
    return this;
  }

  applyFix(index: number): this {
    this.#apply_fix(index);
    return this.#update_diagnostics();
  }

  applyFixes(...fixes: LintFix[]): this {
    this.#apply_fixes(...fixes);
    return this.#update_diagnostics();
  }

  lint(config?: Config): readonly LintDiagnostic[] {
    return this.#update_diagnostics(config).diagnostics;
  }

  fix(config?: Config): readonly LintDiagnostic[] {
    this.#update_diagnostics(config);
    this.#apply_fixes();
    return this.lint(config);
  }

  getRules(): LintRule[] {
    return this.#update_rules().rules;
  }

  formatDiagnostics(noColor?: boolean): string {
    return this.diagnostics.map((d) => d.toString(noColor)).join("\n");
  }

  printDiagnostics(noColor?: boolean, stderr?: boolean): void {
    this.diagnostics.forEach((d) => d.print(noColor, stderr));
  }
}
